version: '3.5'

services:
    next:
        build: infrastructure/node
        environment:
            - NODE_ENV=production
            - HOME=/app/var/cache
            - REACT_ESI_SECRET=secretOnProd
        volumes:
            - .:/app
        working_dir: '/app'
        command: 'npm start'
        user: '${UID}:${GID}'
        extra_hosts:
            - 'react-esi.local:127.0.0.1'
        ports:
            - '3000:3000'

    nginx:
        image: nginx:alpine
        volumes:
            - .:/app
            - ./infrastructure/nginx/site-prod.conf:/etc/nginx/conf.d/default.conf
            - ./infrastructure/tls/:/etc/nginx/conf.d
        depends_on:
            - next
        ports:
            - '443:443'

    varnish:
        build: infrastructure/varnish
        depends_on:
            - next
        volumes:
            - ./infrastructure/varnish/:/usr/local/etc/varnish:ro
        tmpfs:
            - /usr/local/var/varnish:exec
