version: '3.5'

services:
    next:
        image: node:14-alpine
        volumes:
            - .:/app
        working_dir: '/app'
        command: 'npm run dev'
        user: '${UID}:${GID}'
        extra_hosts:
            - 'react-esi.local:127.0.0.1'
        ports:
            - '3000:3000'

    nginx:
        image: nginx:alpine
        volumes:
            - .:/app
            - ./infrastructure/nginx/site.conf:/etc/nginx/conf.d/default.conf
            - ./infrastructure/tls/:/etc/nginx/conf.d
        depends_on:
            - next
        ports:
            - '443:443'
